apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: jenkins-slave-skopeo
  name: jenkins-slave-skopeo
  namespace: cicd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-slave-skopeo:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/siamaksade/jenkins-slave-skopeo.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-base-centos7:latest
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: jenkins-slave-base-centos7:latest
    type: ImageChange
status:
  lastVersion: 0
