apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cicd-project
  source:
    path: gitops/cicd/selenium
    repoURL: git.url.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /status/lastVersion
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: gitops/cicd/selenium
        repoURL: git.url.git
        targetRevision: master
