apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: app-build
    name: petclinic
  name: petclinic-s2i-build
  namespace: cicd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    pushSecret:
      name: quay-cicd-secret
    to:
      kind: DockerImage
      name: quay.io/pittar/petclinic:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: redhat-openjdk18-openshift:1.5
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
